import { useState } from 'react';
import CountUp from 'react-countup';

const DailyCommission = () => {
    const [selectedDate, setSelectedDate] = useState('May 14, 2025');

    // Core Metrics (May 14, 2025)
    const totalCommission = 1800; // ₹1,800
    const yesterdayCommission = 1720; // ₹1,720 (May 13)
    const commissionChange = ((totalCommission - yesterdayCommission) / yesterdayCommission * 100).toFixed(1); // +4.7%
    const commissionTarget = 2500; // ₹2,500
    const progressPercentage = (totalCommission / commissionTarget * 100).toFixed(1); // 72%
    const lastUpdated = "May 28, 2025, 03:27 PM IST"; // Updated to current date and time

    // DOD/HOH Comparison
    const dodCommission = 1720; // May 13: ₹1,720
    const dodChange = commissionChange; // +4.7%
    const lastHourCommission = 90; // 14:57 to 15:57
    const hohChange = ((100 - lastHourCommission) / lastHourCommission * 100).toFixed(1); // +11.1%

    // Advanced: Commission Forecast and Other Metrics
    const predictedCommission = 2711; // Pre-calculated from (1800 / 15.95 * 24).toFixed(0)
    const affiliateCommission = 300; // From Affiliates
    const commissionRefunds = 50; // ₹50 in reversals

    const handleExport = () => {
        // Ensure jsPDF is available in the window object
        const { jsPDF } = window.jspdf;
        if (!jsPDF) {
            alert('jsPDF library is not loaded. Please ensure it is included in your project.');
            return;
        }

        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4',
        });

        // Colors and Fonts
        const primaryColor = '#3b82f6';
        const textColor = '#333333';
        const successColor = '#16a34a';
        const dangerColor = '#ef4444';
        doc.setFont('Helvetica', 'normal');

        // Title
        doc.setFontSize(20);
        doc.setTextColor(primaryColor);
        doc.text('Daily Commission Report', 20, 20);

        // Subtitle (Selected Date)
        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text(`Date: ${selectedDate}`, 20, 30);
        doc.text(`Generated on: ${lastUpdated}`, 20, 38);

        // Section: Core Metrics
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('Core Metrics', 20, 50);

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text(`Total Daily Commission: ${totalCommission.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 20, 60);
        doc.setTextColor(commissionChange >= 0 ? successColor : dangerColor);
        doc.text(`vs Yesterday: ${commissionChange >= 0 ? '+' : ''}${commissionChange}%`, 20, 68);
        doc.setTextColor(textColor);
        doc.text(`Target Progress: ${progressPercentage}% of ${commissionTarget.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 20, 76);

        // Section: DOD/HOH Comparison
        let yPos = 90;
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('DOD/HOH Comparison', 20, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text('DOD Comparison:', 20, yPos);
        doc.setTextColor(dodChange >= 0 ? successColor : dangerColor);
        doc.text(`May 14 vs May 13: ${dodChange >= 0 ? '+' : ''}${dodChange}%`, 30, yPos + 8);
        yPos += 16;

        doc.setTextColor(textColor);
        doc.text('HOH Comparison:', 20, yPos);
        doc.setTextColor(hohChange >= 0 ? successColor : dangerColor);
        doc.text(`15:57 vs 14:57: ${hohChange >= 0 ? '+' : ''}${hohChange}%`, 30, yPos + 8);
        yPos += 16;

        // Section: Advanced Insights
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('Advanced Insights', 20, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text('Commission Forecast:', 20, yPos);
        doc.text(`Predicted EOD: ${parseInt(predictedCommission).toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);
        yPos += 16;

        doc.text('Affiliate Performance:', 20, yPos);
        doc.text(`Referral Commission: ${affiliateCommission.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);
        yPos += 16;

        doc.text('Commission Refunds/Adjustments:', 20, yPos);
        doc.text(`Reversals: ${commissionRefunds.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor('#666666');
        doc.text('Generated by Admin Dashboard', 20, 280);
        doc.text('Page 1 of 1', 180, 280);

        // Download the PDF
        const fileName = `Daily_Commission_${selectedDate.replace(/[^a-zA-Z0-9]/g, '_')}_${lastUpdated.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
        doc.save(fileName);
    };

    return (
        <div className="button-content profit-page">
            {/* Banner */}
            <div className="banner">
                <div className="banner-content">
                    <h1>Daily Commission Overview</h1>
                    <p>A detailed overview of Daily commissions.</p>
                </div>
            </div>

            {/* Controls/Filters */}
            <div className="controls">
                <div className="filter-group">
                    <label htmlFor="dateSelector">Select Date: </label>
                    <select
                        id="dateSelector"
                        value={selectedDate}
                        onChange={(e) => setSelectedDate(e.target.value)}
                    >
                        <option value="May 14, 2025">May 14, 2025</option>
                        <option value="May 13, 2025">May 13, 2025</option>
                        <option value="May 12, 2025">May 12, 2025</option>
                        <option value="May 11, 2025">May 11, 2025</option>
                    </select>
                </div>
                <button className="export-btn" onClick={handleExport}>
                    <ion-icon name="download-outline"></ion-icon> Export Data
                </button>
            </div>

            {/* Core Metrics */}
            <div className="profit-header revenue-header">
                <div className="profit-main">
                    <h2>Total Daily Commission Earned</h2>
                    <div className="profit-amount commission-amount">
                        <CountUp
                            start={0}
                            end={totalCommission}
                            duration={2.5}
                            separator=","
                            prefix="₹"
                            suffix=""
                        />
                    </div>
                    <div className="last-updated">
                        Last Updated: {lastUpdated}
                    </div>
                </div>
                <div className="profit-changes">
                    <div className="change-item">
                        <span>vs Yesterday:</span>
                        <span className={commissionChange >= 0 ? 'change-up' : 'change-down'}>
                            {commissionChange >= 0 ? '▲' : '▼'} {commissionChange}%
                        </span>
                    </div>
                    <div className="progress-box">
                        <h3>Commission Target Progress</h3>
                        <div className="progress-bar">
                            <div
                                className="progress-fill"
                                style={{ width: `${Math.min(progressPercentage, 100)}%` }}
                            ></div>
                        </div>
                        <p>{progressPercentage}% of {commissionTarget.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })} target reached</p>
                    </div>
                </div>
            </div>

            {/* DOD/HOH Comparison */}
          <div className="insights-section_monthly_revenue">
    <div className="insight-box_monthly_revenue">
        <ion-icon name="trending-up-outline"></ion-icon> {/* For DOD Comparison */}
        <div>
            <h3>DOD Comparison</h3>
            <p>May 14 vs May 13: <span className={dodChange >= 0 ? 'change-up' : 'change-down'}>
                {dodChange >= 0 ? '+' : ''}{dodChange}%
            </span></p>
        </div>
    </div>
    <div className="insight-box_monthly_revenue">
        <ion-icon name="time-outline"></ion-icon> {/* For HOH Comparison */}
        <div>
            <h3>HOH Comparison</h3>
            <p>15:57 vs 14:57: <span className={hohChange >= 0 ? 'change-up' : 'change-down'}>
                {hohChange >= 0 ? '+' : ''}{hohChange}%
            </span></p>
        </div>
    </div>
</div>


            {/* Advanced */}
        <div className="revenue-insights-section">
    <div className="commission-forecast-box">
        <ion-icon name="cash-outline"></ion-icon>
        <div>
            <h3>Commission Forecast</h3>
            <p>Predicted EOD: {parseInt(predictedCommission).toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
    <div className="affiliate-performance-box">
        <ion-icon name="people-outline"></ion-icon>
        <div>
            <h3>Affiliate Performance</h3>
            <p>Referral Commission: {affiliateCommission.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
    <div className="commission-refunds-box">
        <ion-icon name="refresh-outline"></ion-icon>
        <div>
            <h3>Commission Refunds/Adjustments</h3>
            <p>Reversals: {commissionRefunds.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
</div>

        </div>
    );
};

export default DailyCommission;