import { useState } from 'react';
import CountUp from 'react-countup';

const MonthlyCommission = () => {
    const [selectedMonth, setSelectedMonth] = useState('May 2025');

    // Core Metrics (May 2025)
    const totalCommission = 24800; // ₹24,800
    const lastMonthCommission = 22900; // ₹22,900 (April 2025)
    const commissionChange = ((totalCommission - lastMonthCommission) / lastMonthCommission * 100).toFixed(1); // +8.3%
    const commissionTarget = 50000; // ₹50,000
    const progressPercentage = (totalCommission / commissionTarget * 100).toFixed(1); // 49.6%
    const lastUpdated = "May 28, 2025, 03:23 PM IST"; // Updated to current date and time

    // YOY/MOM Comparison
    const yoyCommission = 19000; // May 2024: ₹19,000
    const yoyChange = ((totalCommission - yoyCommission) / yoyCommission * 100).toFixed(1); // +30.5%
    const momChange = commissionChange; // +8.3%

    // Advanced: Commission Forecast and Other Metrics
    const predictedCommission = 54857; // Pre-calculated from (24800 / 14 * 31).toFixed(0)
    const affiliateCommission = 5800; // From Affiliates
    const commissionRefunds = 1000; // ₹1,000 in reversals

    const handleExport = () => {
        // Ensure jsPDF is available in the window object
        const { jsPDF } = window.jspdf;
        if (!jsPDF) {
            alert('jsPDF library is not loaded. Please ensure it is included in your project.');
            return;
        }

        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4',
        });

        // Colors and Fonts
        const primaryColor = '#3b82f6';
        const textColor = '#333333';
        const successColor = '#16a34a';
        const dangerColor = '#ef4444';
        doc.setFont('Helvetica', 'normal');

        // Title
        doc.setFontSize(20);
        doc.setTextColor(primaryColor);
        doc.text('Monthly Commission Report', 20, 20);

        // Subtitle (Selected Month)
        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text(`Month: ${selectedMonth}`, 20, 30);
        doc.text(`Generated on: ${lastUpdated}`, 20, 38);

        // Section: Core Metrics
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('Core Metrics', 20, 50);

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text(`Total Monthly Commission: ${totalCommission.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 20, 60);
        doc.setTextColor(commissionChange >= 0 ? successColor : dangerColor);
        doc.text(`vs Last Month: ${commissionChange >= 0 ? '+' : ''}${commissionChange}%`, 20, 68);
        doc.setTextColor(textColor);
        doc.text(`Target Progress: ${progressPercentage}% of ${commissionTarget.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 20, 76);

        // Section: YOY/MOM Comparison
        let yPos = 90;
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('YOY/MOM Comparison', 20, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text('YOY Comparison:', 20, yPos);
        doc.setTextColor(yoyChange >= 0 ? successColor : dangerColor);
        doc.text(`May 2025 vs May 2024: ${yoyChange >= 0 ? '+' : ''}${yoyChange}%`, 30, yPos + 8);
        yPos += 16;

        doc.setTextColor(textColor);
        doc.text('MOM Comparison:', 20, yPos);
        doc.setTextColor(momChange >= 0 ? successColor : dangerColor);
        doc.text(`May 2025 vs Apr 2025: ${momChange >= 0 ? '+' : ''}${momChange}%`, 30, yPos + 8);
        yPos += 16;

        // Section: Advanced Insights
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('Advanced Insights', 20, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text('Commission Forecast:', 20, yPos);
        doc.text(`Predicted EOM: ${parseInt(predictedCommission).toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);
        yPos += 16;

        doc.text('Affiliate Performance:', 20, yPos);
        doc.text(`Referral Commission: ${affiliateCommission.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);
        yPos += 16;

        doc.text('Commission Refunds/Adjustments:', 20, yPos);
        doc.text(`Reversals: ${commissionRefunds.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor('#666666');
        doc.text('Generated by Admin Dashboard', 20, 280);
        doc.text('Page 1 of 1', 180, 280);

        // Download the PDF
        const fileName = `Monthly_Commission_${selectedMonth.replace(' ', '_')}_${lastUpdated.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
        doc.save(fileName);
    };

    return (
        <div className="button-content profit-page">
            {/* Banner */}
            <div className="banner">
                <div className="banner-content">
                    <h1>Monthly Commission Overview</h1>
                    <p>A detailed overview of Monthly commissions.</p>
                </div>
            </div>

            {/* Controls/Filters */}
            <div className="controls">
                <div className="filter-group">
                    <label htmlFor="monthSelector">Select Month: </label>
                    <select
                        id="monthSelector"
                        value={selectedMonth}
                        onChange={(e) => setSelectedMonth(e.target.value)}
                    >
                        <option value="May 2025">May 2025</option>
                        <option value="April 2025">April 2025</option>
                        <option value="March 2025">March 2025</option>
                        <option value="May 2024">May 2024</option>
                    </select>
                </div>
                <button className="export-btn" onClick={handleExport}>
                    <ion-icon name="download-outline"></ion-icon> Export Data
                </button>
            </div>

            {/* Core Metrics */}
            <div className="profit-header revenue-header">
                <div className="profit-main">
                    <h2>Total Monthly Commission Earned</h2>
                    <div className="profit-amount commission-amount">
                        <CountUp
                            start={0}
                            end={totalCommission}
                            duration={2.5}
                            separator=","
                            prefix="₹"
                            suffix=""
                        />
                    </div>
                    <div className="last-updated">
                        Last Updated: {lastUpdated}
                    </div>
                </div>
                <div className="profit-changes">
                    <div className="change-item">
                        <span>vs Last Month:</span>
                        <span className={commissionChange >= 0 ? 'change-up' : 'change-down'}>
                            {commissionChange >= 0 ? '▲' : '▼'} {commissionChange}%
                        </span>
                    </div>
                    <div className="progress-box">
                        <h3>Commission Target Progress</h3>
                        <div className="progress-bar">
                            <div
                                className="progress-fill"
                                style={{ width: `${Math.min(progressPercentage, 100)}%` }}
                            ></div>
                        </div>
                        <p>{progressPercentage}% of {commissionTarget.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })} target reached</p>
                    </div>
                </div>
            </div>

            {/* YOY/MOM Comparison */}
           <div className="insights-section_monthly_revenue">
    <div className="insight-box_monthly_revenue">
        <ion-icon name="trending-up-outline"></ion-icon>
        <div>
            <h3>YOY Comparison</h3>
            <p>May 2025 vs May 2024: <span className={yoyChange >= 0 ? 'change-up' : 'change-down'}>
                {yoyChange >= 0 ? '+' : ''}{yoyChange}%
            </span></p>
        </div>
    </div>
    <div className="insight-box_monthly_revenue">
        <ion-icon name="stats-chart-outline"></ion-icon>
        <div>
            <h3>MOM Comparison</h3>
            <p>May 2025 vs Apr 2025: <span className={momChange >= 0 ? 'change-up' : 'change-down'}>
                {momChange >= 0 ? '+' : ''}{momChange}%
            </span></p>
        </div>
    </div>
</div>


            {/* Advanced */}
      <div className="revenue-insights-section">
    <div className="commission-forecast-box">
        <ion-icon name="cash-outline"></ion-icon>
        <div>
            <h3>Commission Forecast</h3>
            <p>Predicted EOM: {parseInt(predictedCommission).toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
    <div className="affiliate-performance-box">
        <ion-icon name="people-outline"></ion-icon>
        <div>
            <h3>Affiliate Performance</h3>
            <p>Referral Commission: {affiliateCommission.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
    <div className="commission-refunds-box">
        <ion-icon name="refresh-outline"></ion-icon>
        <div>
            <h3>Commission Refunds/Adjustments</h3>
            <p>Reversals: {commissionRefunds.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
</div>

        </div>
    );
};

export default MonthlyCommission;