import { useState } from 'react';
import CountUp from 'react-countup';

const MonthlyRevenue = () => {
    const [selectedMonth, setSelectedMonth] = useState('May 2025');

    // Core info (May 2025)
    const currentRevenue = 124000; // ₹1,24,000
    const lastMonthRevenue = 114500; // ₹1,14,500 (April 2025)
    const revenueChange = ((currentRevenue - lastMonthRevenue) / lastMonthRevenue * 100).toFixed(1); // +8.3%
    const revenueTarget = 200000; // ₹2,00,000
    const progressPercentage = (currentRevenue / revenueTarget * 100).toFixed(1); // 74%
    const lastUpdated = "May 14, 2025, 03:02 PM IST";

    // YOY/MOM Comparison
    const yoyRevenue = 95000; // May 2024: ₹95,000
    const yoyChange = ((currentRevenue - yoyRevenue) / yoyRevenue * 100).toFixed(1); // +30.5%
    const momChange = revenueChange; // +8.3%

    // Advanced Options
    const activeUsersRevenue = 90000; // ₹90,000
    const passiveUsersRevenue = 34000; // ₹34,000
    const referredUsersRevenue = 15000; // ₹15,000
    const churnImpact = 5000; // ₹5,000 loss due to churn

    const handleExport = () => {
        // Ensure jsPDF is available in the window object
        const { jsPDF } = window.jspdf;
        if (!jsPDF) {
            alert('jsPDF library is not loaded. Please ensure it is included in your project.');
            return;
        }

        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4',
        });

        // Colors and Fonts
        const primaryColor = '#3b82f6';
        const textColor = '#333333';
        const successColor = '#16a34a';
        const dangerColor = '#ef4444';
        doc.setFont('Helvetica', 'normal');

        // Title
        doc.setFontSize(20);
        doc.setTextColor(primaryColor);
        doc.text('Monthly Revenue Report', 20, 20);

        // Subtitle (Selected Month)
        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text(`Month: ${selectedMonth}`, 20, 30);
        doc.text(`Generated on: ${lastUpdated}`, 20, 38);

        // Section: Core Info
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('Core Info', 20, 50);

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text(`Current Month's Revenue: ${currentRevenue.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 20, 60);
        doc.setTextColor(revenueChange >= 0 ? successColor : dangerColor);
        doc.text(`vs Last Month: ${revenueChange >= 0 ? '+' : ''}${revenueChange}%`, 20, 68);
        doc.setTextColor(textColor);
        doc.text(`Target Progress: ${progressPercentage}% of ${revenueTarget.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 20, 76);

        // Section: YOY/MOM Comparison
        let yPos = 90;
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('YOY/MOM Comparison', 20, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text('YOY Comparison:', 20, yPos);
        doc.setTextColor(yoyChange >= 0 ? successColor : dangerColor);
        doc.text(`May 2025 vs May 2024: ${yoyChange >= 0 ? '+' : ''}${yoyChange}%`, 30, yPos + 8);
        yPos += 16;

        doc.setTextColor(textColor);
        doc.text('MOM Comparison:', 20, yPos);
        doc.setTextColor(momChange >= 0 ? successColor : dangerColor);
        doc.text(`May 2025 vs Apr 2025: ${momChange >= 0 ? '+' : ''}${momChange}%`, 30, yPos + 8);
        yPos += 16;

        // Section: Advanced Options
        doc.setFontSize(16);
        doc.setTextColor(primaryColor);
        doc.text('Advanced Options', 20, yPos);
        yPos += 10;

        doc.setFontSize(12);
        doc.setTextColor(textColor);
        doc.text('Active vs Passive Users:', 20, yPos);
        doc.text(`Active: ${activeUsersRevenue.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);
        doc.text(`Passive: ${passiveUsersRevenue.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 16);
        yPos += 24;

        doc.text('Revenue from Referred Users:', 20, yPos);
        doc.text(`${referredUsersRevenue.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);
        yPos += 16;

        doc.text('Subscription Churn Impact:', 20, yPos);
        doc.text(`Estimated Loss: ${churnImpact.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}`, 30, yPos + 8);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor('#666666');
        doc.text('Generated by Admin Dashboard', 20, 280);
        doc.text('Page 1 of 1', 180, 280);

        // Download the PDF
        const fileName = `Monthly_Revenue_${selectedMonth.replace(' ', '_')}_${lastUpdated.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
        doc.save(fileName);
    };

    return (
        <div className="button-content profit-page">
            {/* Banner */}
            <div className="banner">
                <div className="banner-content">
                    <h1>Monthly Revenue Overview</h1>
                    <p>A comprehensive overview of Monthly revenue.</p>
                </div>
            </div>

            {/* Controls/Filters */}
            <div className="controls">
                <div className="filter-group">
                    <label htmlFor="monthSelector">Select Month: </label>
                    <select
                        id="monthSelector"
                        value={selectedMonth}
                        onChange={(e) => setSelectedMonth(e.target.value)}
                    >
                        <option value="May 2025">May 2025</option>
                        <option value="April 2025">April 2025</option>
                        <option value="March 2025">March 2025</option>
                        <option value="May 2024">May 2024</option>
                    </select>
                </div>
                <button className="export-btn" onClick={handleExport}>
                    <ion-icon name="download-outline"></ion-icon> Export Data
                </button>
            </div>

            {/* Core Info */}
            <div className="profit-header revenue-header">
                <div className="profit-main">
                    <h2>Current Month’s Revenue</h2>
                    <div className="profit-amount revenue-amount">
                        <CountUp
                            start={0}
                            end={currentRevenue}
                            duration={2.5}
                            separator=","
                            prefix="₹"
                            suffix=""
                        />
                    </div>
                    <div className="last-updated">
                        Last Updated: {lastUpdated}
                    </div>
                </div>
                <div className="profit-changes">
                    <div className="change-item">
                        <span>vs Last Month:</span>
                        <span className={revenueChange >= 0 ? 'change-up' : 'change-down'}>
                            {revenueChange >= 0 ? '▲' : '▼'} {revenueChange}%
                        </span>
                    </div>
                    <div className="progress-box">
                        <h3>Revenue Target Progress</h3>
                        <div className="progress-bar">
                            <div
                                className="progress-fill"
                                style={{ width: `${Math.min(progressPercentage, 100)}%` }}
                            ></div>
                        </div>
                        <p>{progressPercentage}% of {revenueTarget.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })} target reached</p>
                    </div>
                </div>
            </div>

            {/* YOY/MOM Comparison */}
<div className="insights-section_monthly_revenue">
    <div className="insight-box_monthly_revenue">
        <ion-icon name="trending-up-outline"></ion-icon>
        <div>
            <h3>YOY Comparison</h3>
            <p>May 2025 vs May 2024: <span className={yoyChange >= 0 ? 'change-up' : 'change-down'}>
                {yoyChange >= 0 ? '+' : ''}{yoyChange}%
            </span></p>
        </div>
    </div>
    <div className="insight-box_monthly_revenue">
        <ion-icon name="trending-up-outline"></ion-icon>
        <div>
            <h3>MOM Comparison</h3>
            <p>May 2025 vs Apr 2025: <span className={momChange >= 0 ? 'change-up' : 'change-down'}>
                {momChange >= 0 ? '+' : ''}{momChange}%
            </span></p>
        </div>
    </div>
</div>



       {/* Advanced Options */}
<div className="revenue-insights-section">
    <div className="active-passive-users-box">
        <ion-icon name="person-outline"></ion-icon>
        <div>
            <h3>Active vs Passive Users</h3>
            <p>Active: {activeUsersRevenue.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
            <p>Passive: {passiveUsersRevenue.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
    <div className="referred-users-revenue-box">
        <ion-icon name="share-social-outline"></ion-icon>
        <div>
            <h3>Revenue from Referred Users</h3>
            <p>{referredUsersRevenue.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
    <div className="subscription-churn-impact-box">
        <ion-icon name="trending-down-outline"></ion-icon>
        <div>
            <h3>Subscription Churn Impact</h3>
            <p>Estimated Loss: {churnImpact.toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</p>
        </div>
    </div>
</div>
        </div>
    );
};

export default MonthlyRevenue;